# Generated by Django 4.1.7 on 2023-10-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_delete_newuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
