# Generated by Django 4.1.7 on 2023-10-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_user_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='profile_image',
            new_name='profile_image1',
        ),
        migrations.AlterModelTable(
            name='user1',
            table='User1',
        ),
    ]
