# Generated by Django 4.1.7 on 2023-10-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_profile_image_user1_profile_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='profile_image1',
            new_name='profile_image',
        ),
    ]
