# Generated by Django 4.1.7 on 2023-10-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_profile_image1_user1_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
