# Generated by Django 4.0.5 on 2022-06-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_bookmark_like_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='feed_id',
            field=models.IntegerField(default=''),
        ),
    ]
