# Generated by Django 4.0.5 on 2022-06-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_reply_feed_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
    ]
