# Generated by Django 4.0.5 on 2022-06-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_feed_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('email', models.CharField(max_length=254)),
                ('is_marked', models.IntegerField()),
            ],
            options={
                'db_table': 'content_bookmark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.TextField()),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'content_feed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('email', models.CharField(max_length=254)),
                ('is_like', models.IntegerField()),
            ],
            options={
                'db_table': 'content_like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('feed_id', models.IntegerField()),
                ('reply_content', models.TextField()),
            ],
            options={
                'db_table': 'content_reply',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
